### ISSUE TITLE
Deprecation Error

### ISSUE THREAD

**Issue by dackdel** [mobarski/ask-my-pdf#1]
DeprecationError: PdfFileReader is deprecated and was removed in PyPDF2 3.0.0. Use PdfReader instead.

Have you tried pdfplumber instead?

**Comment by mobarski** [comment]
I'll try it, thank you. I've used a snippet from my old project and decided, that I'll handle the problems later. If you install the project dependencies with "pip install -r requirements.txt" the old version of PyPDF will be used. I should fix this over the weekend.

**Comment by mobarski** [comment]
I've tested pdfplumber. PyPDF is much better with multicolumn documents. I'll rewrite the code to use PdfReader in place of PdfFileReader.

**Comment by mobarski** [comment]
I've merged the branch that uses the newest pypdf and doesn't use deprecated functions.
